### PR TITLE
Bring simulator to be usable with terra and finalize syntax

### PR DESCRIPTION
**Pull request by dcmckayibm**

### CODE REVIEW

**Comment by nonhermitian** [comment]
Note that you will not be able to simulate the full device Hamiltonian in your example.  You have 20 qubits and ~32 qubits more worth of oscillator Hamiltonian.  This is why the Hamiltonian needs to be truncated.

**Comment by dcmckayibm** [comment]
Rebased to your changes

**Comment by dcmckayibm** [comment]
After rebasing, I can run the notebook I made before (note I moved it to /example/). Next would be to check it can run through a standard aer path (instead of calling digest and opsolve directly).

**Comment by dcmckayibm** [comment]
So it can now run through the standard path (I needed to format the unitary solver output, which was only done for the MC solver). Need to check with noise.

**Pull request merged**
